### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/BERT-Question-Generation#1]
Traceback (most recent call last):
  File "train_seq2seq_QG.py", line 804, in <module>
    main()
  File "train_seq2seq_QG.py", line 799, in main
    global_step, tr_loss = train(args, model, tokenizer)
  File "train_seq2seq_QG.py", line 426, in train
    outputs = model(**inputs)
  File "/home/ubuntu/anaconda3/envs/py38mj/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py38mj/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/py38mj/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/py38mj/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/ubuntu/anaconda3/envs/py38mj/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py38mj/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py38mj/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'labels'

**Comment by minji-o-j** [comment]
`outputs = model(**inputs)` 에서 에러

```py
inputs = {
                "input_ids": batch[0],
                "attention_mask": batch[1],
                "token_type_ids": batch[2],
                "labels": batch[3],
            }
```

bert는 label 안넘어가나?
https://stackoverflow.com/questions/58454157/pytorch-bert-typeerror-forward-got-an-unexpected-keyword-argument-labels

- y

![image](https://user-images.githubusercontent.com/45448731/169210441-7e8a242f-2e6b-4991-b3ac-fa82c80b9da7.png)
